# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Angie Tigger
email: aalmrazg7@gmail.com
theme: jekyll-theme-merlot
#description: > # this means to ignore newlines until "baseurl:"
#  Enthusiast of new technologies, I like to develop and design 
#  apps for Mobile/Web Platforms, integrating IoT (Internet of Things),
#  using new Technologies (java, javascript and web).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aalmaraz.github.io/blog/" # the base hostname & protocol for your site
github_username:  aalmaraz
# Build settings
markdown: kramdown
#paginate: 7
# Gems
gems: [jekyll-paginate]